Parameters:
  AnthropicToken:
    Type: String
    NoEcho: true
    Description: Anthropic API token
Resources:
  Anthropic:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Anthropic API token
      SecretString: !Sub '{"token": "${AnthropicToken}"}'
Outputs:
  AnthropicSecretArn:
    Value: !Ref Anthropic