Parameters:
  AnthropicToken:
    Type: String
    NoEcho: true
    Description: Anthropic API token
Resources:
  Anthropic:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: anthropic/token
      Description: Anthropic API token
      SecretString: !Sub '{"token": "${AnthropicToken}"'